### ISSUE TITLE
add-user, remove-user, grant,revoke, enable-user, disable-user

### ISSUE THREAD

**Issue by esunar** [canonical/juju-spell#77]
For juju to allow access to model you need to execute below commands.
```bash
juju add-user $USER
juju grant $USER superuser
juju enable-user $USER
for model in $(juju models --format=json | jq '.models[]."short-name"' | tr -d '"'); do
  juju grant $USER admin $model
done
```
In real life I've seen no one uses anything other than superuser.
I would prefer just 2 commands add-user, remove user
**add-user**
`juju-spell add-user <user> --acl <superuser, readonly> --models <model1,model2>`
if acl is `superuser` it will execute
```bash
juju add-user $USER # (if not exists)
juju grant $USER superuser
juju enable-user $USER
for model in $MODELS; do
  echo "juju grant $USER admin $model"
done
```
if acl is `readonly` it will execute
```bash
juju add-user $USER  # (if not exists)
juju grant $USER login # (revoke if it has higher permissions)
juju enable-user $USER
for model in $MODELS; do
  echo "juju grant $USER read $model"  # (revoke if it has higher permissions)
done
```
**remove-user**
`juju-spell remove-user <user>`
Since in juju it is impossible to add removed user. Thus I propose to remove all user privileges and disable user. 
```bash
for model in $(juju models --format=json | jq '.models[]."short-name"' | tr -d '"'); do
  juju revoke $USER read $model"
done
juju revoke $USER login
juju disable-user $USER
```

**Comment by rgildein** [comment]
@esunar The problem here is that you cannot add user which was already removed. We can revoke and disable-user instead of removing it and in part of adding users we simply check if user exists and if not create it.

**Comment by jneo8** [comment]
The models access levels are `read`, `write`, and `admin`.
So we gone to ignore `write`?

**Comment by esunar** [comment]
We can do this, but I do not know a use case for `write`.

**Comment by jneo8** [comment]
I think we still raise error if user exists in add-usre cmd.
But update grant cmd to available to grant model permission.

**Comment by rgildein** [comment]
@jneo8 I think that we agreed that we will have only `add-user` and `remove-user`, no `grant` or `enable`?

**Comment by jneo8** [comment]
We already have grant & enable, so I think the solution is to call grant/enable in add-user/remove-user instead of remove them.
