### ISSUE TITLE
Potential regression from PR #76

### ISSUE THREAD

**Issue by chanchiwai-ray** [canonical/juju-spell#82]
Potential regression from PR #76: after running `make dev-environment`, I start seeing this

```bash
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	juju_spell.egg-info/

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by rgildein** [comment]
@chanchiwai-ray Can you please update our .gitignore templates [bootstack-charms-spec](https://launchpad.net/bootstack-charms-spec) and than use it in juju-spell. Thanks
